### ISSUE TITLE
Async controller function returns empty object always

### ISSUE THREAD

**Issue by JLaferri** [nishant-labs/node-rest-server#31]
My use case specifically is that I'm using Firebase auth and Apollo client to access user data from my endpoint. Without supporting an async controller function and using `await` on my external function calls, I don't know how else I would return the data I want to the API consumer.

**Comment by JLaferri** [comment]
Addressed in https://github.com/nishant-labs/node-rest-server/pull/30

**Comment by nishant-labs** [comment]
Thanks for sharing use case.

This gives me an idea of adding async support for filters as well so that user can do some server manipulation(this is on me). Following issue with cover rest of the implementation #32

**Comment by nishant-labs** [comment]
@JLaferri PR is merged, will soon publish a new version with the change.

Let me know if you find any bug :+1:
