### ISSUE TITLE
Put, Delete and Patch?!

### ISSUE THREAD

**Issue by atguim** [nishant-labs/node-rest-server#50]
Where is put, delete and patch methods?!
The link documentation not working!

**Comment by nishant-labs** [comment]
You can use any HTTP method

```
const routeConfig = {
	'/path': {
		method: 'PUT',
		status: 200,
		controller: () => {},
	}
};
```

Thanks for pointing out, I will fix the example link however you can use below link

https://github.com/nishant-labs/node-rest-server/tree/master/examples

**Comment by nishant-labs** [comment]
The example is link fixed

Also fix an issue where the empty response wasn't processed correctly
